Adding 2 new messages 0x8012 and 0x9999
zigpy/zigpy-zigate pull request #107
Opened 2021-12-10 18:42 UTC by pipiche38

2021-12-10 18:43 UTC, pipiche38 commented
@doudz , don't where the changes on Application.py are coming from.

2021-12-15 20:14 UTC, doudz requested changes
Could you also add a unit test to validate two stages pairing ?

2021-12-15 20:14 UTC, doudz commented on zigpy_zigate/api.py
> +    0x8012: (t.uint8_t, t.uint8_t, t.uint8_t, t.Address, t.uint8_t),
Duplicated line

2021-12-15 20:14 UTC, doudz commented on zigpy_zigate/zigbee/application.py
> +            #time.sleep(2.0)
Please remove commented line

2021-12-15 20:14 UTC, doudz commented on zigpy_zigate/zigbee/application.py
> +            #self.handle_join(nwk, ieee, parent_nwk)
same

2021-12-15 20:17 UTC, doudz requested changes

2021-12-15 20:17 UTC, doudz commented on zigpy_zigate/zigbee/application.py
> +            rejoin = response[3]
You should also update line 47 to set minimal firmware to 3.2

2021-12-15 20:19 UTC, doudz requested changes

2021-12-15 20:19 UTC, doudz commented on zigpy_zigate/api.py
> +    0x9999: (t.uint8_t,),
You should also handle the message with logger

2021-12-16 08:23 UTC, pipiche38 commented
Ok. will leave @badz handling.

2021-12-16 08:23 UTC, closed without merging

2021-12-30 08:58 UTC, pipiche38 commented
we are currently working on zigpy-zigate library under a fork dedicated to our project, we don't have the possibility to test it under the ZHA environment but if you are ready to do, you can eventually use it
https://github.com/zigbeefordomoticz/zigpy-zigate

When ready we will be providing PRs against the main stream